sudo: required
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.7.1

script:
  - docker-compose --file docker-compose-build.yml up -d --build
  - docker-compose --file docker-compose-build.yml run web nginx -t
  - docker-compose --file docker-compose-build.yml run fpm php -v
  - docker-compose --file docker-compose-build.yml run cli php -v
  - docker-compose --file docker-compose-build.yml run cli kickass-installer
