version: "2"
services:
  web:
    build:
      context: nginx/
    environment:
      - VIRTUAL_HOST=dev.kickasscommerce.com
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - 80
    links:
      - fpm
    volumes_from:
      - appdata

  fpm:
    hostname: fpm.kickasscommerce.docker
    build:
      context: 7.1-fpm/
    ports:
      - 9000
    volumes_from:
      - appdata

  cli:
    hostname: cli.kickasscommerce.docker
    build:
      context: 7.1-cli/
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    volumes_from:
      - appdata
    environment:
      - KICKASS_VERSION=dev-develop

  appdata:
    image: tianon/true
    volumes:
      - ./kickass:/var/www/kickass
