version: "2"
services:
  web:
    build:
      context: nginx/
    ports:
      - 80
    volumes_from:
      - appdata

  appdata:
    image: tianon/true
    volumes:
      - ./kickass:/var/www/kickass
